sudo: required

language: bash

before_install:
  - sudo apt-get update
  - sudo apt-get update -q
  - export scversion="stable" # or "v0.4.7", or "latest"
  - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
  - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
  - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
  - /usr/bin/shellcheck --version

  - sudo apt-get install imagemagick
  - wget "https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/worldcupplayerinfo.tsv"
  - wget "https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z"
  - sudo apt install p7zip-full
  - 7z x web_log.tsv.7z

script:
  - bash chap0x04/code/task1.sh -h
  - bash chap0x04/code/task1.sh -d chap0x04/image -c 80
  - bash chap0x04/code/task1.sh -d chap0x04/image -r 25%
  - bash chap0x04/code/task1.sh -d chap0x04/image -a blue 20 NewDividedc
  - bash chap0x04/code/task1.sh -d chap0x04/image -p pre
  - bash chap0x04/code/task1.sh -d chap0x04/image -s zyy
  - bash chap0x04/code/task1.sh -d chap0x04/image -t
  - printf "\n"
  - bash chap0x04/code/task2.sh -h
  - bash chap0x04/code/task2.sh -a 
  - bash chap0x04/code/task2.sh -b
  - bash chap0x04/code/task2.sh -c 
  - bash chap0x04/code/task2.sh -d 
  - printf "\n"
  - bash chap0x04/code/task3.sh -h
  - bash chap0x04/code/task3.sh -a
  - bash chap0x04/code/task3.sh -b
  - bash chap0x04/code/task3.sh -c
  - bash chap0x04/code/task3.sh -d
  - bash chap0x04/code/task3.sh -e
  - bash chap0x04/code/task3.sh -s /history/apollo/images/apollo-small.gif

after_script:
  - /usr/bin/shellcheck chap0x04/code/task1.sh
  - /usr/bin/shellcheck chap0x04/code/task2.sh
  - /usr/bin/shellcheck chap0x04/code/task3.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log
 
notifications:
  email:
    on_success: never

